version: '3'
services:
  app:
    build: ./app
    ports:
    - 3000:3000
    environment:
      - PORT=3000
    networks:
      - sidecar-pattern-net
  proxy_server:
    build: ./nginx
    ports:
    - 8080:80
    environment:
      - NGINX_HOST=app:3000
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - sidecar-pattern-net
networks:
  sidecar-pattern-net:
    driver: bridge
