version: '3'
services:
  app:
    build: ./app
    ports:
    - 3000:3000
    networks:
      - sidecar-pattern-net
  proxy_server:
    build: ./nginx
    ports:
    - 8080:80
    networks:
      - sidecar-pattern-net
networks:
  sidecar-pattern-net:
    driver: bridge
